apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  annotations:
    kubernetes.io/change-cause: "Update jenkinsfile on 2025-11-11 17:48:45"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-dep
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
      labels:
        app: backend-dep
    spec:
      containers:
        - name: node-backend
          image: clarozzz/k8s-backend:187
          ports:
            - containerPort: 3001
          env:
            - name: DB_USER
              value: my-user
            - name: DB_PASS
              value: test
            - name: DB_NAME
              value: todos
            - name: DB_HOST
              value: postgres-svc
            - name: PORT
              value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: backend-svc
spec:
  selector:
    app: backend-dep
  ports:
    - protocol: TCP
      port: 3001

      targetPort: 3001



