apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
  annotations:
    kubernetes.io/change-cause: "Update jenkinsfile on 2025-11-11 17:48:45"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app: frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-dep
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
      labels:
        app: frontend-dep
    spec:
      containers:
        - name: vite-frontend
          image: clarozzz/k8s-frontend:187
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_URL
              value: http://backend-svc:3001
            - name: test_1
              value: test_1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: frontend-svc
spec:
  selector:
    app: frontend-dep
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: LoadBalancer



